<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SafeBite_Backend_H6.Load</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>6432c61a-2d16-47c2-893a-bebdbd11a92a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
    <PackageReference Include="NBomber" Version="6.3.0" />
    <PackageReference Include="NBomber.Http" Version="6.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SafeBite-Backend-H6.API\SafeBite-Backend-H6.API.csproj" />
  </ItemGroup>

</Project>
