services:
  postgres:
    image: postgres:16
    container_name: safebitevH6-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: safebitevH6_app
    ports:
      - "55432:5432"
    volumes:
      - safebitevH6_postgres_data:/var/lib/postgresql/data

volumes:
  safebitevH6_postgres_data: