// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafeBite_Backend_H6.API.Data.AppDb;

#nullable disable

namespace SafeBite_Backend_H6.API.Data.Migrations.App
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SafeBite_Backend_H6.API.Entities.Allergies.Allergy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("SafeBite_Backend_H6.API.Entities.Allergies.AllergyUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("AllergyId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "AllergyId");

                    b.HasIndex("AllergyId");

                    b.HasIndex("UserId");

                    b.ToTable("AllergyUsers");
                });

            modelBuilder.Entity("SafeBite_Backend_H6.API.Entities.Allergies.CustomAllergy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("CustomAllergies");
                });

            modelBuilder.Entity("SafeBite_Backend_H6.API.Entities.Scans.DetectedIngredientMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IngredientText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ScanDetectedAllergyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ScanDetectedAllergyId", "IngredientText")
                        .IsUnique();

                    b.ToTable("DetectedIngredientMatches");
                });

            modelBuilder.Entity("SafeBite_Backend_H6.API.Entities.Scans.Scan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScannedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("SafeBite_Backend_H6.API.Entities.Scans.ScanDetectedAllergies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllergyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AllergyId");

                    b.HasIndex("ScanId", "AllergyId")
                        .IsUnique();

                    b.ToTable("ScanDetectedAllergies");
                });

            modelBuilder.Entity("SafeBite_Backend_H6.API.Entities.Allergies.AllergyUser", b =>
                {
                    b.HasOne("SafeBite_Backend_H6.API.Entities.Allergies.Allergy", "Allergy")
                        .WithMany("AllergyUser")
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergy");
                });

            modelBuilder.Entity("SafeBite_Backend_H6.API.Entities.Scans.DetectedIngredientMatch", b =>
                {
                    b.HasOne("SafeBite_Backend_H6.API.Entities.Scans.ScanDetectedAllergies", "ScanDetectedAllergy")
                        .WithMany("MatchedIngredients")
                        .HasForeignKey("ScanDetectedAllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanDetectedAllergy");
                });

            modelBuilder.Entity("SafeBite_Backend_H6.API.Entities.Scans.ScanDetectedAllergies", b =>
                {
                    b.HasOne("SafeBite_Backend_H6.API.Entities.Allergies.Allergy", "Allergy")
                        .WithMany("ScanDetectedAllergies")
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafeBite_Backend_H6.API.Entities.Scans.Scan", "Scan")
                        .WithMany("DetectedAllergies")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("SafeBite_Backend_H6.API.Entities.Allergies.Allergy", b =>
                {
                    b.Navigation("AllergyUser");

                    b.Navigation("ScanDetectedAllergies");
                });

            modelBuilder.Entity("SafeBite_Backend_H6.API.Entities.Scans.Scan", b =>
                {
                    b.Navigation("DetectedAllergies");
                });

            modelBuilder.Entity("SafeBite_Backend_H6.API.Entities.Scans.ScanDetectedAllergies", b =>
                {
                    b.Navigation("MatchedIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
